name: OnPush

on:
  push:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: macos-latest

    steps:
      
      - uses: actions/checkout@v3

      - name: Set up JDK 16
        uses: actions/setup-java@v3

        with:
          java-version: '16'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn test --file pom.xml
        
       # mvn clean test

     # - name: Maven Verify
        # mvn -B clean verify
